name: Deploy to GitHub Pages

on:
  push:
    tags:
      - 'v*' # Trigger on version tags (e.g., v1.0.0)

# Add permissions block
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # Only run on tags
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for tags
          ref: ${{ github.ref }}  # Use the tag reference

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Inject version and build number
        run: node inject-version.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true
          single-commit: true  # Create a single commit instead of multiple commits 