name: Test Build

on:
  push:
    branches:
      - main  # or master, depending on your default branch
  pull_request:
    branches:
      - main  # or master, depending on your default branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Test build
        run: npm run build

      - name: Run tests
        run: npm test 